version: '3'
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: always
    network_mode: host
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
      - ./log:/root/.npm/_logs
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0
    restart: always
    network_mode: host
    privileged: true
    environment:
      - TZ=Europe/Madrid