homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost'
serial:
  port: /dev/ttyACM0
devices:
  '0x00158d0002520b26':
    friendly_name: door_window_xiaomi/SENSOR
  '0x00158d00047b5824':
    friendly_name: temperature_humidity_xiaomi/SENSOR
  '0x00158d0002567d32':
    friendly_name: motion_xiaomi/SENSOR